const express=require("express")
var cors = require('cors')
require('dotenv').config()
const db = require("./config/db")
const auth = require("./routers/auth")
const products = require("./routers/products")
const cartdt = require("./routers/cartdt")
const order = require("./routers/order")
const server=express()
server.use(express.json())
server.use(cors())
server.use(express.urlencoded({extended:true}))
db.connect()
server.use("/api/auth/",auth)
server.use("/api/products/",products)
server.use("/api/cartdt/",cartdt)
server.use("/api/order/",order)
server.use("/api/Imgproducts/",express.static("../server/src/public/img"))
server.use("/api/ImgUser/",express.static("../server/src/public/user"))
module.exports=server